apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-letsencrypt-certificate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-letsencrypt-certificate.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.secret.valuesAreBase64Encoded }}
  account.json: {{.Values.secret.letsencryptAccountJson | toString}}
  account.key: {{.Values.secret.letsencryptAccountKey | toString}}
  cloudflareApiEmail: {{.Values.secret.cloudflareApiEmail | toString}}
  cloudflareApiKey: {{.Values.secret.cloudflareApiKey | toString}}
  {{- else }}
  account.json: {{.Values.secret.letsencryptAccountJson | toString | b64enc}}
  account.key: {{.Values.secret.letsencryptAccountKey | toString | b64enc}}
  cloudflareApiEmail: {{.Values.secret.cloudflareApiEmail | toString | b64enc}}
  cloudflareApiKey: {{.Values.secret.cloudflareApiKey | toString | b64enc}}
  {{- end }}