labels:
  app: estafette-letsencrypt-certificate
  team: estafette-team
  language: golang

pipelines:
  build:
    image: golang:1.8.0-alpine
    workDir: /go/src/github.com/estafette/estafette-letsencrypt-certificate
    commands:
    - go test ./...
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: docker:17.03.0-ce
    commands:
    - cp Dockerfile ./publish
    - cp /etc/ssl/certs/ca-certificates.crt ./publish
    - docker build -t ${ESTAFETTE_LABEL_APP} ./publish
    - ls -latr ./publish
    - rm -rf ./publish