apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: estafette-letsencrypt-certificate
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]