apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: estafette-letsencrypt-certificate
  labels:
{{ include "commonLabels" . | indent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  verbs:
  - list
- apiGroups: [""] # "" indicates the core/v1 API group
  resources:
  - events
  verbs:
  - create
  - get
  - update
