apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-letsencrypt-certificate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-letsencrypt-certificate.labels" . | indent 4 }}
type: Opaque
data:
  account.json: {{.Values.secret.letsencryptAccountJson | b64enc}}
  account.key: {{.Values.secret.letsencryptAccountKey | b64enc}}
  cloudflareApiEmail: {{.Values.secret.cloudflareApiEmail | b64enc}}
  cloudflareApiKey: {{.Values.secret.cloudflareApiKey | b64enc}}